const posts = [
  {
    id: 1,
    name: 'Cruz',
    image: 'https://randomuser.me/api/portraits/med/men/23.jpg',
    city: 'San Vito al Tagliamento',
    country: 'Kyrgyzstan',
    text: 'risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor',
    likes: 108,
    comments: 89,
    commentImage: 'https://randomuser.me/api/portraits/med/men/52.jpg',
    commentText:
      'turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus',
  },
  {
    id: 2,
    name: 'Chadwick',
    image: 'https://randomuser.me/api/portraits/med/men/32.jpg',
    city: 'Urbe',
    country: 'Sri Lanka',
    text: 'sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum',
    likes: 125,
    comments: 32,
    commentImage: 'https://randomuser.me/api/portraits/med/men/53.jpg',
    commentText:
      'eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam',
  },
  {
    id: 3,
    name: 'Acton',
    image: 'https://randomuser.me/api/portraits/med/men/16.jpg',
    city: 'Husum',
    country: 'Heard Island and Mcdonald Islands',
    text: 'interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non,',
    likes: 114,
    comments: 77,
    commentImage: 'https://randomuser.me/api/portraits/med/men/54.jpg',
    commentText:
      'ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor',
  },
  {
    id: 4,
    name: 'Harding',
    image: 'https://randomuser.me/api/portraits/med/men/15.jpg',
    city: 'Froidchapelle',
    country: 'Bosnia and Herzegovina',
    text: 'et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac,',
    likes: 164,
    comments: 70,
    commentImage: 'https://randomuser.me/api/portraits/med/men/55.jpg',
    commentText:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec',
  },
  {
    id: 5,
    name: 'Beck',
    image: 'https://randomuser.me/api/portraits/med/men/14.jpg',
    city: 'Landau',
    country: 'Tajikistan',
    text: 'quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper,',
    likes: 54,
    comments: 81,
    commentImage: 'https://randomuser.me/api/portraits/med/men/56.jpg',
    commentText: 'ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id,',
  },
  {
    id: 6,
    name: 'Cody',
    image: 'https://randomuser.me/api/portraits/med/men/13.jpg',
    city: 'Wollongong',
    country: 'Korea, North',
    text: 'orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae',
    likes: 137,
    comments: 112,
    commentImage: 'https://randomuser.me/api/portraits/med/men/57.jpg',
    commentText:
      'hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna.',
  },
  {
    id: 7,
    name: 'Logan',
    image: 'https://randomuser.me/api/portraits/med/men/12.jpg',
    city: 'Mazatlán',
    country: 'Philippines',
    text: 'justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit',
    likes: 93,
    comments: 118,
    commentImage: 'https://randomuser.me/api/portraits/med/men/58.jpg',
    commentText:
      'lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam',
  },
  {
    id: 8,
    name: 'Macon',
    image: 'https://randomuser.me/api/portraits/med/men/61.jpg',
    city: 'Saharanpur',
    country: 'Senegal',
    text: 'parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et',
    likes: 193,
    comments: 108,
    commentImage: 'https://randomuser.me/api/portraits/med/men/62.jpg',
    commentText:
      'Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur',
  },
  {
    id: 9,
    name: 'Grady',
    image: 'https://randomuser.me/api/portraits/med/men/63.jpg',
    city: 'Sint-Ulriks-Kapelle',
    country: 'Macao',
    text: 'sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis',
    likes: 122,
    comments: 76,
    commentImage: 'https://randomuser.me/api/portraits/med/men/64.jpg',
    commentText:
      'ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper',
  },
  {
    id: 10,
    name: 'Eagan',
    image: 'https://randomuser.me/api/portraits/med/men/9.jpg',
    city: 'Lisciano Niccone',
    country: 'Chad',
    text: 'ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales',
    likes: 165,
    comments: 35,
    commentImage: 'https://randomuser.me/api/portraits/med/men/65.jpg',
    commentText:
      'Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus',
  },
  {
    id: 11,
    name: 'Gannon',
    image: 'https://randomuser.me/api/portraits/med/men/8.jpg',
    city: 'Torella del Sannio',
    country: 'Zimbabwe',
    text: 'Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus.',
    likes: 41,
    comments: 71,
    commentImage: 'https://randomuser.me/api/portraits/med/men/71.jpg',
    commentText: 'neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra.',
  },
  {
    id: 12,
    name: 'Grant',
    image: 'https://randomuser.me/api/portraits/med/men/7.jpg',
    city: 'Vöcklabruck',
    country: 'Antarctica',
    text: 'eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci,',
    likes: 127,
    comments: 27,
    commentImage: 'https://randomuser.me/api/portraits/med/men/72.jpg',
    commentText:
      'leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu',
  },
  {
    id: 13,
    name: 'Kennan',
    image: 'https://randomuser.me/api/portraits/med/men/6.jpg',
    city: 'Saint-Remy-Geest',
    country: 'Switzerland',
    text: 'id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus',
    likes: 87,
    comments: 117,
    commentImage: 'https://randomuser.me/api/portraits/med/men/73.jpg',
    commentText:
      'leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper.',
  },
  {
    id: 14,
    name: 'Ivan',
    image: 'https://randomuser.me/api/portraits/med/men/5.jpg',
    city: 'Isle-aux-Coudres',
    country: 'Tanzania',
    text: 'scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec',
    likes: 177,
    comments: 58,
    commentImage: 'https://randomuser.me/api/portraits/med/men/15.jpg',
    commentText:
      'rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit',
  },
  {
    id: 15,
    name: 'Stephen',
    image: 'https://randomuser.me/api/portraits/med/men/4.jpg',
    city: 'Saint-Nicolas',
    country: 'Albania',
    text: 'at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique',
    likes: 47,
    comments: 29,
    commentImage: 'https://randomuser.me/api/portraits/med/men/74.jpg',
    commentText:
      'ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem.',
  },
  {
    id: 16,
    name: 'Sebastian',
    image: 'https://randomuser.me/api/portraits/med/men/3.jpg',
    city: 'Portofino',
    country: 'Nicaragua',
    text: 'eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae',
    likes: 46,
    comments: 26,
    commentImage: 'https://randomuser.me/api/portraits/med/men/15.jpg',
    commentText:
      'luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,',
  },
  {
    id: 17,
    name: 'Cain',
    image: 'https://randomuser.me/api/portraits/med/men/2.jpg',
    city: 'Eberswalde-Finow',
    country: 'Azerbaijan',
    text: 'convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus.',
    likes: 63,
    comments: 113,
    commentImage: 'https://randomuser.me/api/portraits/med/men/76.jpg',
    commentText:
      'Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum',
  },
  {
    id: 18,
    name: 'Callum',
    image: 'https://randomuser.me/api/portraits/med/men/1.jpg',
    city: 'Merzig',
    country: 'Aruba',
    text: 'dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non,',
    likes: 53,
    comments: 82,
    commentImage: 'https://randomuser.me/api/portraits/med/men/91.jpg',
    commentText:
      'rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,',
  },
  {
    id: 19,
    name: 'Judah',
    image: 'https://randomuser.me/api/portraits/med/men/89.jpg',
    city: 'Rio Grande',
    country: 'Egypt',
    text: 'Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget,',
    likes: 166,
    comments: 106,
    commentImage: 'https://randomuser.me/api/portraits/med/men/41.jpg',
    commentText:
      'molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum',
  },
  {
    id: 20,
    name: 'Elijah',
    image: 'https://randomuser.me/api/portraits/med/men/90.jpg',
    city: 'Besançon',
    country: 'Virgin Islands, United States',
    text: 'blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula.',
    likes: 63,
    comments: 41,
    commentImage: 'https://randomuser.me/api/portraits/med/men/42.jpg',
    commentText: 'risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,',
  },
];

export default posts;
